package ui;

import dao.MovieDAO;
import javax.swing.JOptionPane;
import model.Movie;

public class AddMovieFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddMovieFrame.class.getName());

    /**
     * Creates new form MovieManagementFrame
     */
    public AddMovieFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGenre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRating = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnViewMovies = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEMAX - Add New Movie");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 26, 31));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(35, 39, 47));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Title:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 110, -1));
        jPanel3.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 330, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Genre:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 110, -1));
        jPanel3.add(txtGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 330, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Duration:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 110, -1));
        jPanel3.add(txtDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 330, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Rating:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 110, -1));
        jPanel3.add(txtRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 330, -1));

        btnSave.setBackground(new java.awt.Color(222, 47, 62));
        btnSave.setText("Save Movie");
        btnSave.addActionListener(this::btnSaveActionPerformed);
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel3.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        btnViewMovies.setText("View Movies");
        btnViewMovies.addActionListener(this::btnViewMoviesActionPerformed);
        jPanel3.add(btnViewMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        btnDashboard.setText("Back To Dashboard");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);
        jPanel3.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 150, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 840, 430));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add New Movie");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 330, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        setSize(new java.awt.Dimension(914, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String title = txtTitle.getText().trim();
            String genre = txtGenre.getText().trim();
            String durationMinutes = txtDuration.getText().trim();
            String rating = txtRating.getText().trim();

            if(title.isEmpty() ||
               genre.isEmpty() ||
               durationMinutes.isEmpty() ||
               rating.isEmpty()) {

                JOptionPane.showMessageDialog(
                        this,
                        "Please fill all fields");
                return;
            }

            try {

                Integer.parseInt(durationMinutes);

            } catch(NumberFormatException e) {

                JOptionPane.showMessageDialog(
                        this,
                        "Duration must be a number");
                return;
            }

            Movie movie = new Movie();
            movie.setTitle(title);
            movie.setGenre(genre);
            movie.setDurationMinutes(Integer.parseInt(durationMinutes));
            movie.setRating(rating);

            MovieDAO dao = new MovieDAO();

            if (dao.addMovie(movie)) {

                JOptionPane.showMessageDialog(
                        this,
                        "Movie Saved Successfully");

                txtTitle.setText("");
                txtGenre.setText("");
                txtDuration.setText("");
                txtRating.setText("");
            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Movie save failed");
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        new AdminDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtTitle.setText("");
        txtGenre.setText("");
        txtDuration.setText("");
        txtRating.setText("");

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnViewMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMoviesActionPerformed
        new ManageMovieFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewMoviesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddMovieFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnViewMovies;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
