package ui;

import javax.swing.JOptionPane;
import util.UserSession;

public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnManageUsers = new javax.swing.JButton();
        btnAddMovie = new javax.swing.JButton();
        btnManageMovies = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btlLogin = new javax.swing.JButton();
        btnManageShowtimes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEMAX - Admin Dashboard");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 39, 47));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageUsers.setBackground(new java.awt.Color(222, 47, 62));
        btnManageUsers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnManageUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUsers.setText("Manage Users");
        btnManageUsers.setActionCommand("");
        btnManageUsers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageUsers.addActionListener(this::btnManageUsersActionPerformed);
        jPanel1.add(btnManageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 260, 170));

        btnAddMovie.setBackground(new java.awt.Color(222, 47, 62));
        btnAddMovie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddMovie.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMovie.setText("Add Movies");
        btnAddMovie.setActionCommand("");
        btnAddMovie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddMovie.addActionListener(this::btnAddMovieActionPerformed);
        jPanel1.add(btnAddMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 170));

        btnManageMovies.setBackground(new java.awt.Color(222, 47, 62));
        btnManageMovies.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnManageMovies.setForeground(new java.awt.Color(255, 255, 255));
        btnManageMovies.setText("Manage Movies");
        btnManageMovies.setActionCommand("");
        btnManageMovies.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageMovies.addActionListener(this::btnManageMoviesActionPerformed);
        jPanel1.add(btnManageMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 260, 170));

        btnReports.setBackground(new java.awt.Color(222, 47, 62));
        btnReports.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setText("Reports");
        btnReports.setToolTipText("");
        btnReports.addActionListener(this::btnReportsActionPerformed);
        jPanel1.add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 260, 170));

        btlLogin.setBackground(java.awt.Color.darkGray);
        btlLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btlLogin.setForeground(new java.awt.Color(255, 255, 255));
        btlLogin.setText("Back To Login");
        btlLogin.addActionListener(this::btlLoginActionPerformed);
        jPanel1.add(btlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 260, 170));

        btnManageShowtimes.setBackground(new java.awt.Color(222, 47, 62));
        btnManageShowtimes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnManageShowtimes.setForeground(new java.awt.Color(255, 255, 255));
        btnManageShowtimes.setText("Manage Showtimes");
        btnManageShowtimes.setActionCommand("");
        btnManageShowtimes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageShowtimes.addActionListener(this::btnManageShowtimesActionPerformed);
        jPanel1.add(btnManageShowtimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 260, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 870, 420));

        jPanel2.setBackground(new java.awt.Color(24, 26, 31));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Cinema Admin Potal");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 380, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 550));

        setSize(new java.awt.Dimension(925, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMoviesActionPerformed
        ManageMovieFrame movies = new ManageMovieFrame();
        movies.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageMoviesActionPerformed

    private void btnManageShowtimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageShowtimesActionPerformed
        ShowTimeFrame showtimes = new ShowTimeFrame();
        showtimes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageShowtimesActionPerformed

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
        new ManageUsersFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageUsersActionPerformed

    private void btnAddMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMovieActionPerformed
       new AddMovieFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnAddMovieActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        new ReportFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btlLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlLoginActionPerformed
        UserSession.clear();
        new LoginFrame().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btlLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlLogin;
    private javax.swing.JButton btnAddMovie;
    private javax.swing.JButton btnManageMovies;
    private javax.swing.JButton btnManageShowtimes;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JButton btnReports;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
