package ui;

import dao.MovieDAO;
import dao.SeatDAO;
import dao.ShowTimeDAO;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Movie;
import model.Seat;
import model.ShowTime;
import util.UserSession;

public class BookingFrame extends javax.swing.JFrame {

    private final Map<Integer, ShowTime> showTimesById = new HashMap<>();
    private final Map<Integer, Seat> seatsById = new HashMap<>();
    
    private void loadShowTimes(int movieId){

    cmbShowTime.removeAllItems();
    cmbSeat.removeAllItems();

    cmbShowTime.setEnabled(true);
    cmbSeat.setEnabled(false);

    showTimesById.clear();
    seatsById.clear();

    ShowTimeDAO dao =
            new ShowTimeDAO();

    for(ShowTime s :
            dao.getShowTimesByMovie(movieId)){

        showTimesById.put(s.getShowtimeId(), s);

        cmbShowTime.addItem(

                s.getShowtimeId()
                + " | "
                + s.getShowDate()
                + " "
                + s.getShowTime()
        );
    }
    
    if(cmbShowTime.getItemCount() == 0){

        JOptionPane.showMessageDialog(
                this,
                "No showtimes available for this movie.");

        cmbShowTime.setEnabled(false);
        cmbSeat.setEnabled(false);
    }

    if(cmbShowTime.getItemCount() > 0){
        cmbShowTime.setSelectedIndex(0);
        loadSeatsForSelectedShowTime();
    }
}
    
        private void loadMovies() {

        DefaultTableModel model =
                (DefaultTableModel) tblMovies.getModel();

        model.setRowCount(0);

        MovieDAO dao = new MovieDAO();

        for(Movie movie : dao.getAllMovies()) {

            model.addRow(new Object[]{

                movie.getMovieId(),
                movie.getTitle(),
                movie.getGenre(),
                movie.getDurationMinutes(),
                movie.getRating()
            });
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingFrame.class.getName());

    /**
     * Creates new form BookingFrame
     */
    public BookingFrame() {
        initComponents();
        cmbShowTime.removeAllItems();
        cmbSeat.removeAllItems();

        cmbShowTime.setEnabled(false);
        cmbSeat.setEnabled(false);

        loadMovies();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovies = new javax.swing.JTable();
        cmbShowTime = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnBook = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbSeat = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEMAX - Bookings");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book Tickets");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        tblMovies.setAutoCreateRowSorter(true);
        tblMovies.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tblMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Movie ID", "Movie Name", "Genre", "Duration(min)", "Rating"
            }
        ));
        tblMovies.setColumnSelectionAllowed(true);
        tblMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMoviesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMovies);
        tblMovies.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblMovies.getColumnModel().getColumnCount() > 0) {
            tblMovies.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 840, 360));

        cmbShowTime.addActionListener(this::cmbShowTimeActionPerformed);
        getContentPane().add(cmbShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 210, 30));

        jPanel1.setBackground(new java.awt.Color(24, 26, 31));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBook.setBackground(new java.awt.Color(222, 47, 62));
        btnBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBook.setText("Book");
        btnBook.addActionListener(this::btnBookActionPerformed);
        jPanel1.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, -1, -1));

        btnBack.setBackground(java.awt.Color.darkGray);
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(242, 242, 242));
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 60, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Seat:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, 30));

        cmbSeat.addActionListener(this::cmbSeatActionPerformed);
        jPanel1.add(cmbSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 260, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Show Time:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(914, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblMoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMoviesMouseClicked

    int row =
            tblMovies.getSelectedRow();

    if(row >= 0){

        int movieId =
                Integer.parseInt(
                        tblMovies.getValueAt(
                                row,
                                0).toString());

        loadShowTimes(movieId);
    }
        
    }//GEN-LAST:event_tblMoviesMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new CustomerDashboard().setVisible(true);
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed

    if(tblMovies.getSelectedRow() == -1){
        JOptionPane.showMessageDialog(
                this,
                "Please select a movie first.");
        return;
    }

    if(cmbShowTime.getSelectedItem() == null){
        JOptionPane.showMessageDialog(
                this,
                "Please select a show time.");
        return;
    }

    if(cmbSeat.getSelectedItem() == null){
        JOptionPane.showMessageDialog(
                this,
                "Please select a seat.");
        return;
    }

    int userId = UserSession.getCurrentUserId();

    if(userId <= 0){

        JOptionPane.showMessageDialog(
                this,
                "Please login before making a booking.");

        new LoginFrame().setVisible(true);
        dispose();

        return;
    }

    int row = tblMovies.getSelectedRow();

    String movie =
            tblMovies.getValueAt(row, 1).toString();

    String showTime =
            cmbShowTime.getSelectedItem().toString();

    String seatText =
            cmbSeat.getSelectedItem().toString();

    int showtimeId =
            getSelectedId(cmbShowTime.getSelectedItem());

    int seatId =
            getSelectedId(cmbSeat.getSelectedItem());

    Seat seat =
            seatsById.get(seatId);

    double amount =
            calculatePrice(seat);

    PaymentFrame pf =
            new PaymentFrame(
                    userId,
                    showtimeId,
                    seatId,
                    movie,
                    showTime,
                    seatText,
                    amount);

    pf.setVisible(true);

    this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnBookActionPerformed

    private void cmbSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeatActionPerformed
    }//GEN-LAST:event_cmbSeatActionPerformed

    private void cmbShowTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbShowTimeActionPerformed
        if(cmbShowTime.getSelectedItem() != null){
            cmbSeat.setEnabled(true);
            loadSeatsForSelectedShowTime();
        }
         // TODO add your handling code here:
    }//GEN-LAST:event_cmbShowTimeActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadMovies();

        cmbShowTime.removeAllItems();
        cmbSeat.removeAllItems();

        cmbShowTime.setEnabled(false);
        cmbSeat.setEnabled(false);

        showTimesById.clear();
        seatsById.clear();
    // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed


    private void loadSeatsForSelectedShowTime(){
        int showtimeId = getSelectedId(cmbShowTime.getSelectedItem());
        ShowTime showTime = showTimesById.get(showtimeId);

        cmbSeat.removeAllItems();
        seatsById.clear();

        if(showTime == null){
            return;
        }

        SeatDAO seatDAO = new SeatDAO();
        List<Seat> seats = seatDAO.getAvailableSeats(
                showTime.getShowtimeId(),
                showTime.getHallNo());

        for(Seat seat : seats){
            seatsById.put(seat.getSeatId(), seat);
            cmbSeat.addItem(
                    seat.getSeatId()
                    + " | "
                    + seat.getSeatRow()
                    + seat.getSeatNumber()
                    + " | "
                    + seat.getSeatType()
                    + " | Rs. "
                    + String.format("%.2f", calculatePrice(seat)));
        }
        
        if(cmbSeat.getItemCount() == 0){

            JOptionPane.showMessageDialog(
                    this,
                    "No seats available for this showtime.");

            cmbSeat.setEnabled(false);
        }
    }

    private int getSelectedId(Object selectedItem){
        if(selectedItem == null){
            return 0;
        }

        String value = selectedItem.toString();
        int separator = value.indexOf('|');
        String idText = separator >= 0
                ? value.substring(0, separator).trim()
                : value.trim();

        try{
            return Integer.parseInt(idText);
        }catch(NumberFormatException e){
            return 0;
        }
    }

    private double calculatePrice(Seat seat){
        if(seat == null || seat.getSeatType() == null){
            return 1000.00;
        }

        return switch(seat.getSeatType().toUpperCase()){
            case "VIP" -> 2000.00;
            case "PREMIUM" -> 1500.00;
            default -> 1000.00;
        };
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cmbSeat;
    private javax.swing.JComboBox<String> cmbShowTime;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMovies;
    // End of variables declaration//GEN-END:variables
}
