package ui;

import dao.MovieDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Movie;

public class ManageMovieFrame extends javax.swing.JFrame {
    
    private void loadMovies(){

    DefaultTableModel model =
            (DefaultTableModel) tblMovies.getModel();

    model.setRowCount(0);

    MovieDAO dao =
            new MovieDAO();

        for(Movie movie :
                dao.getAllMovies()){

            model.addRow(
                    new Object[]{

                            movie.getMovieId(),
                            movie.getTitle(),
                            movie.getGenre(),
                            movie.getDurationMinutes(),
                            movie.getRating()
                    });
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageMovieFrame.class.getName());

    /**
     * Creates new form MovieManagementFrame
     */
    public ManageMovieFrame() {
    initComponents();
    loadMovies();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovies = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEMAX - Manage Movies");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(242, 242, 242));
        lblSearch.setText("Search Movie:");
        getContentPane().add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 300, 27));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Movies");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 300, -1));

        btnSearch.setBackground(java.awt.Color.darkGray);
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(242, 242, 242));
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        tblMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Genre", "Duration", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMovies.setColumnSelectionAllowed(true);
        tblMovies.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblMovies);
        tblMovies.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 810, 290));

        jPanel1.setBackground(new java.awt.Color(24, 26, 31));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(914, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

    String keyword =
            txtSearch.getText();

    DefaultTableModel model =
            (DefaultTableModel)
                    tblMovies.getModel();

    model.setRowCount(0);

    MovieDAO dao =
            new MovieDAO();

    for(Movie movie :
            dao.searchMovies(keyword)){

        model.addRow(
                new Object[]{

                        movie.getMovieId(),
                        movie.getTitle(),
                        movie.getGenre(),
                        movie.getDurationMinutes(),
                        movie.getRating()
                });
    }
   
// TODO: Query database for movies matching keyword
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadMovies();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       new AddMovieFrame().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    int row = tblMovies.getSelectedRow();

    if(row == -1){

        JOptionPane.showMessageDialog(
                this,
                "Select a movie");

        return;
    }
    
    int confirm =
        JOptionPane.showConfirmDialog(
                this,
                "Delete this movie?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);

    if(confirm !=
            JOptionPane.YES_OPTION){
        return;
    }

    int movieId =
            Integer.parseInt(
                    tblMovies.getValueAt(
                            row,
                            0).toString());

    MovieDAO dao =
            new MovieDAO();

    if(dao.deleteMovie(movieId)){

        JOptionPane.showMessageDialog(
                this,
                "Movie Deleted");

        loadMovies();

    }else{

        JOptionPane.showConfirmDialog(
                this,
                "Delete Failed");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

    int row = tblMovies.getSelectedRow();

    if(row == -1){
        JOptionPane.showMessageDialog(
                this,
                "Select a movie first");
        return;
    }

        int movieId = Integer.parseInt(
            tblMovies.getValueAt(row, 0).toString());

        String title = JOptionPane.showInputDialog(
                this,
                "Enter New Title",
                tblMovies.getValueAt(row,1));

        String genre = JOptionPane.showInputDialog(
                this,
                "Enter New Genre",
                tblMovies.getValueAt(row,2));

        String duration = JOptionPane.showInputDialog(
                this,
                "Enter New Duration",
                tblMovies.getValueAt(row,3));

        String rating = JOptionPane.showInputDialog(
                this,
                "Enter New Rating",
                tblMovies.getValueAt(row,4));

        if(title == null || genre == null ||
           duration == null || rating == null){
            return;
        }

        try{

            int durationValue =
                    Integer.parseInt(duration);

            Movie movie = new Movie();

            movie.setMovieId(movieId);
            movie.setTitle(title);
            movie.setGenre(genre);
            movie.setDurationMinutes(durationValue);
            movie.setRating(rating);

            MovieDAO dao =
                    new MovieDAO();

            if(dao.updateMovie(movie)){

                JOptionPane.showMessageDialog(
                        this,
                        "Movie Updated Successfully");

                loadMovies();

            }else{

                JOptionPane.showMessageDialog(
                        this,
                        "Update Failed");
            }
            }catch(NumberFormatException e){

                JOptionPane.showMessageDialog(
                        this,
                        "Duration must be numeric");

            }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageMovieFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblMovies;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
