package ui;

import dao.SeatDAO;
import java.sql.SQLException;
import model.Seat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageSeatsFrame extends javax.swing.JFrame {
    
    private SeatDAO seatDAO =
        new SeatDAO();
    
    private void loadSeats(){

    DefaultTableModel model =
            (DefaultTableModel)
                    tblSeats.getModel();

    model.setRowCount(0);

    List<Seat> seats =
            seatDAO.getAllSeats();

    for(Seat seat : seats){

        model.addRow(new Object[]{

            seat.getSeatId(),
            seat.getHallId(),
            seat.getSeatRow(),
            seat.getSeatNumber(),
            seat.getSeatType()
        });
    }
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageSeatsFrame.class.getName());

    /**
     * Creates new form ManageSeatsFrame
     */
    public ManageSeatsFrame() {
        initComponents();
        loadSeats();

        cmbSeatType.removeAllItems();
        cmbSeatType.addItem("REGULAR");
        cmbSeatType.addItem("PREMIUM");
        cmbSeatType.addItem("VIP");
    }
    
    private void clearFields(){

    txtSeatId.setText("");
    txtSeatId.setText("");
    txtSeatRow.setText("");
    txtSeatNumber.setText("");

    cmbSeatType.setSelectedIndex(0);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeats = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblhallid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSeatNumber = new javax.swing.JTextField();
        txtSeatId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSeatRow = new javax.swing.JTextField();
        cmbSeatType = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtHallId = new javax.swing.JTextField();
        lblhallid1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 26, 31));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSeats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Seat ID", "Hall ID", "Seat Raw", "Seat Number", "Seat Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSeats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeatsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSeats);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 820, 250));

        jPanel2.setBackground(new java.awt.Color(35, 39, 47));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhallid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblhallid.setForeground(new java.awt.Color(242, 242, 242));
        lblhallid.setText("Seat ID:");
        jPanel2.add(lblhallid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Seat Number:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Seat Raw:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        txtSeatNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtSeatNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 140, -1));

        txtSeatId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtSeatId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Seat Type:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        txtSeatRow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtSeatRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 140, -1));

        cmbSeatType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbSeatType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGULAR", "PREMIUM", "VIP" }));
        jPanel2.add(cmbSeatType, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 140, -1));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add Seat");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 90, 40));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 80, 40));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 80, 40));

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        jPanel2.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 80, 40));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("Back");
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 80, 40));

        txtHallId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtHallId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 140, -1));

        lblhallid1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblhallid1.setForeground(new java.awt.Color(242, 242, 242));
        lblhallid1.setText("Hall ID:");
        jPanel2.add(lblhallid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 860, 440));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Seats");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
            if(txtSeatId.getText().isEmpty()){

        JOptionPane.showMessageDialog(
                this,
                "Select Seat First");

        return;
    }

    int seatId =
            Integer.parseInt(
                    txtSeatId.getText());

    if(seatDAO.deleteSeat(seatId)){

        JOptionPane.showMessageDialog(
                this,
                "Seat Deleted");

        loadSeats();
        clearFields();

    }else{

        JOptionPane.showMessageDialog(
                this,
                "Delete Failed");
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

    try{

        Seat seat =
                new Seat();

        seat.setHallId(
                Integer.parseInt(
                        txtSeatId.getText()));

        seat.setSeatRow(
                txtSeatRow.getText());

        seat.setSeatNumber(
                Integer.parseInt(
                        txtSeatNumber.getText()));

        seat.setSeatType(
                cmbSeatType
                        .getSelectedItem()
                        .toString());

        if(seatDAO.addSeat(seat)){

            JOptionPane.showMessageDialog(
                    this,
                    "Seat Added Successfully");

            loadSeats();
            clearFields();

        }else{

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to Add Seat");
        }

    }catch(Exception e){

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try{

            Seat seat =
                    new Seat();

            seat.setSeatId(
                    Integer.parseInt(
                            txtSeatId.getText()));

            seat.setHallId(
                    Integer.parseInt(
                            txtHallId.getText()));

            seat.setSeatRow(
                    txtSeatRow.getText());

            seat.setSeatNumber(
                    Integer.parseInt(
                            txtSeatNumber.getText()));

            seat.setSeatType(
                    cmbSeatType
                            .getSelectedItem()
                            .toString());

            if(seatDAO.updateSeat(seat)){

                JOptionPane.showMessageDialog(
                        this,
                        "Seat Updated");

                loadSeats();
                clearFields();

            }else{

                JOptionPane.showMessageDialog(
                        this,
                        "Update Failed");
            }

        }catch(Exception e){

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage());
        }


// TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadSeats();
        clearFields();
// TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblSeatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeatsMouseClicked
    int row =
            tblSeats.getSelectedRow();

    txtSeatId.setText(
            tblSeats.getValueAt(row,0)
                    .toString());

    txtHallId.setText(
            tblSeats.getValueAt(row,1)
                    .toString());

    txtSeatRow.setText(
            tblSeats.getValueAt(row,2)
                    .toString());

    txtSeatNumber.setText(
            tblSeats.getValueAt(row,3)
                    .toString());

    cmbSeatType.setSelectedItem(
            tblSeats.getValueAt(row,4)
                    .toString());
       // TODO add your handling code here:
    }//GEN-LAST:event_tblSeatsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageSeatsFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSeatType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblhallid;
    private javax.swing.JLabel lblhallid1;
    private javax.swing.JTable tblSeats;
    private javax.swing.JTextField txtHallId;
    private javax.swing.JTextField txtSeatId;
    private javax.swing.JTextField txtSeatNumber;
    private javax.swing.JTextField txtSeatRow;
    // End of variables declaration//GEN-END:variables
}
