/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.BookingDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Booking;
import util.UserSession;

/**
 *
 * @author Thilan
 */
public class MyBookingFrame extends javax.swing.JFrame {
    
    private void loadBookings(){

    DefaultTableModel model =
            (DefaultTableModel)
                    tblBookings.getModel();

    model.setRowCount(0);

    BookingDAO dao =
            new BookingDAO();

        try{

            List<Booking> bookings =
                    dao.getBookingsByUser(
                            UserSession.getCurrentUserId());

            for(Booking booking : bookings){

                model.addRow(
                        new Object[]{

                                booking.getBookingId(),

                                booking.getMovieTitle(),

                                booking.getShowDate(),

                                booking.getShowTime(),

                                booking.getSeat(),

                                booking.getTotalPrice(),

                                booking.getStatus()
                        });
            }

        }catch(Exception e){

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage());
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyBookingFrame.class.getName());

    /**
     * Creates new form MyBookingFrame
     */
    public MyBookingFrame() {
        initComponents();
        loadBookings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookings = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCancelBooking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEMAX - My Bookings");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 26, 31));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("My Bookings");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        tblBookings.setBackground(new java.awt.Color(153, 153, 153));
        tblBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Movie", "Date", "Time", "Seat", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBookings);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 800, 320));

        btnRefresh.setBackground(java.awt.Color.darkGray);
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(242, 242, 242));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, 40));

        btnBack.setBackground(java.awt.Color.darkGray);
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(242, 242, 242));
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, 40));

        btnCancelBooking.setBackground(java.awt.Color.darkGray);
        btnCancelBooking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelBooking.setForeground(new java.awt.Color(242, 242, 242));
        btnCancelBooking.setText("Cancel Booking");
        btnCancelBooking.addActionListener(this::btnCancelBookingActionPerformed);
        jPanel1.add(btnCancelBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        setSize(new java.awt.Dimension(914, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadBookings();
// TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new CustomerDashboard().setVisible(true);
        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelBookingActionPerformed
        
        int row =
            tblBookings.getSelectedRow();

    if(row == -1){

        JOptionPane.showMessageDialog(
                this,
                "Select a booking");

        return;
    }

    int bookingId =
            Integer.parseInt(
                    tblBookings.getValueAt(
                            row,
                            0).toString());

    String status =
            tblBookings.getValueAt(
                    row,
                    6).toString();

    if(status.equalsIgnoreCase(
            Booking.STATUS_CANCELLED)){

        JOptionPane.showMessageDialog(
                this,
                "Already Cancelled");

        return;
    }
    
    BookingDAO dao =
            new BookingDAO();

    if(dao.cancelBooking(bookingId)){

        JOptionPane.showMessageDialog(
                this,
                "Booking Cancelled");

        loadBookings();

    }else{

        JOptionPane.showMessageDialog(
                this,
                "Cancel Failed");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MyBookingFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelBooking;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBookings;
    // End of variables declaration//GEN-END:variables
}
