package ui;

import dao.BookingDAO;
import javax.swing.JOptionPane;
import model.Booking;

public class PaymentFrame extends javax.swing.JFrame {
    
    private int userId;
    private int showtimeId;
    private int seatId;
    private double amount;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaymentFrame.class.getName());

    public PaymentFrame(
        int userId,
        int showtimeId,
        int seatId,
        String movie,
        String showTime,
        String seat,
        double amount) {

    initComponents();

    this.userId = userId;
    this.showtimeId = showtimeId;
    this.seatId = seatId;
    this.amount = amount;

    txtMovie.setText(movie);
    txtShowTime.setText(showTime);
    txtSeat.setText(seat);
    txtAmount.setText(String.valueOf(amount));

    txtMovie.setEditable(false);
    txtShowTime.setEditable(false);
    txtSeat.setEditable(false);
    txtAmount.setEditable(false);
}

    public PaymentFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCardHolder = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtMovie = new javax.swing.JTextField();
        txtShowTime = new javax.swing.JTextField();
        txtSeat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtExpiry = new javax.swing.JTextField();
        txtCVV = new javax.swing.JTextField();
        btnPayNow = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEMAX - Payments");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 26, 31));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Payment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Movie:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ShowTime:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Seat:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Payment Method(Credit / Debit)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Card Number:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        txtCardNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtCardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 240, 28));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Card Holder:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        txtCardHolder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtCardHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 240, 28));

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("(M/D)");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 325, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Expiry      :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("CVV:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        jPanel2.setBackground(new java.awt.Color(35, 39, 47));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMovie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 240, 28));

        txtShowTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 240, 28));

        txtSeat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 240, 28));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 242, 242));
        jLabel10.setText("Amount:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAmount.addActionListener(this::txtAmountActionPerformed);
        jPanel2.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 220, 28));

        txtExpiry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtExpiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 150, 28));

        txtCVV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCVV.setToolTipText("");
        jPanel2.add(txtCVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 60, 28));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 860, 340));

        btnPayNow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPayNow.setText("PayNow");
        btnPayNow.addActionListener(this::btnPayNowActionPerformed);
        jPanel1.add(btnPayNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(914, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnPayNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayNowActionPerformed

    String cardNumber =
            txtCardNumber.getText().trim();

    String cardHolder =
            txtCardHolder.getText().trim();

    String expiry =
            txtExpiry.getText().trim();

    String cvv =
            txtCVV.getText().trim();

    if(cardNumber.isEmpty()){

        JOptionPane.showMessageDialog(
                this,
                "Enter Card Number");

        return;
    }

    if(!cardNumber.matches("\\d{16}")){

        JOptionPane.showMessageDialog(
                this,
                "Card Number must be 16 digits");

        return;
    }

    if(cardHolder.isEmpty()){

        JOptionPane.showMessageDialog(
                this,
                "Enter Card Holder Name");

        return;
    }

    if(!expiry.matches("(0[1-9]|1[0-2])/\\d{2}")){

        JOptionPane.showMessageDialog(
                this,
                "Enter Expiry Date");

        return;
    }

    if(!cvv.matches("\\d{3}")){

        JOptionPane.showMessageDialog(
                this,
                "CVV must be 3 digits");

        return;
    }

    Booking booking =
            new Booking();

    booking.setUserId(userId);
    booking.setShowtimeId(showtimeId);
    booking.setTotalPrice(amount);
    booking.setStatus("CONFIRMED");

    BookingDAO dao =
            new BookingDAO();

    int bookingId =
            dao.createBooking(booking);

    if(bookingId > 0 &&
            dao.addBookingSeat(
                    bookingId,
                    seatId)){

        JOptionPane.showMessageDialog(
                this,
                "Payment Successful!\nBooking Confirmed.");

        new MyBookingFrame()
                .setVisible(true);

        dispose();

    }else{

        JOptionPane.showMessageDialog(
                this,
                "Booking Failed.");
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayNowActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new BookingFrame().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PaymentFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPayNow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtCardHolder;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtExpiry;
    private javax.swing.JTextField txtMovie;
    private javax.swing.JTextField txtSeat;
    private javax.swing.JTextField txtShowTime;
    // End of variables declaration//GEN-END:variables
}
