package ui;

import dao.BookingDAO;
import dao.MovieDAO;
import dao.SeatDAO;
import dao.ShowTimeDAO;
import dao.UserDAO;
import javax.swing.JOptionPane;

public class ReportFrame extends javax.swing.JFrame {
    
    private void loadReport(){

        int totalMovies =
                movieDAO.getTotalMovies();

        int totalUsers =
                userDAO.getTotalUsers();

        int totalShowtimes =
                showTimeDAO.getTotalShowTimes();

        int totalBookings =
                bookingDAO.getTotalBookings();

        double revenue =
                bookingDAO.getTotalRevenue();

        int totalSeats =
                seatDAO.getTotalShowSeats();    

        lblTotalMovies.setText(
                String.valueOf(totalMovies));

        lblUsers.setText(
                String.valueOf(totalUsers));

        lblShowtimes.setText(
                String.valueOf(totalShowtimes));

        lblBookings.setText(
                String.valueOf(totalBookings));

        lblRevenue.setText(
                "Rs. "
                + String.format("%.2f", revenue));

        int bookedSeats =
            bookingDAO.getBookedSeatsCount();

        double occupancy = 0.0;

        if (totalSeats > 0) {
            occupancy = (bookedSeats * 100.0) / totalSeats;
        }

        lblOccupancy.setText(
                String.format(
                        "%.2f%%",
                        occupancy));
    }
    
    private final MovieDAO movieDAO =
        new MovieDAO();

    private final UserDAO userDAO =
            new UserDAO();

    private final ShowTimeDAO showTimeDAO =
            new ShowTimeDAO();

    private final BookingDAO bookingDAO =
            new BookingDAO();

    private final SeatDAO seatDAO =
            new SeatDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportFrame.class.getName());

    /**
     * Creates new form ReportFrame
     */
    public ReportFrame() {
        initComponents();
        loadReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTotalMovies = new javax.swing.JLabel();
        lblBookings = new javax.swing.JLabel();
        btnLoadReport = new javax.swing.JButton();
        lblShowtimes = new javax.swing.JLabel();
        lblUsers = new javax.swing.JLabel();
        lblOccupancy = new javax.swing.JLabel();
        lblRevenue = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEMAX - Statistics");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(24, 26, 31));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(178, 185, 196));
        jLabel3.setText("Total Movies");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(178, 185, 196));
        jLabel5.setText("Revenue");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(178, 185, 196));
        jLabel6.setText("Occupancy");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(178, 185, 196));
        jLabel7.setText("Total Users");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(178, 185, 196));
        jLabel4.setText("Bookings");
        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        btnDashboard.setBackground(new java.awt.Color(102, 102, 102));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(242, 242, 242));
        btnDashboard.setText("Back");
        btnDashboard.setToolTipText("");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);
        jPanel2.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 70, 30));

        btnLogout.setBackground(new java.awt.Color(102, 102, 102));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(242, 242, 242));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 77, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(178, 185, 196));
        jLabel1.setText("Showtimes");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        lblTotalMovies.setBackground(new java.awt.Color(35, 39, 47));
        lblTotalMovies.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalMovies.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalMovies.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalMovies.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 39, 47), 1, true));
        jPanel2.add(lblTotalMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 380, 120));

        lblBookings.setBackground(new java.awt.Color(35, 39, 47));
        lblBookings.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBookings.setForeground(new java.awt.Color(242, 242, 242));
        lblBookings.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 39, 47), 1, true));
        jPanel2.add(lblBookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 380, 120));

        btnLoadReport.setBackground(new java.awt.Color(102, 102, 102));
        btnLoadReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoadReport.setForeground(new java.awt.Color(242, 242, 242));
        btnLoadReport.setText("Load Report");
        btnLoadReport.addActionListener(this::btnLoadReportActionPerformed);
        jPanel2.add(btnLoadReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, 30));

        lblShowtimes.setBackground(new java.awt.Color(35, 39, 47));
        lblShowtimes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblShowtimes.setForeground(new java.awt.Color(242, 242, 242));
        lblShowtimes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 39, 47), 1, true));
        jPanel2.add(lblShowtimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 380, 120));

        lblUsers.setBackground(new java.awt.Color(35, 39, 47));
        lblUsers.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUsers.setForeground(new java.awt.Color(242, 242, 242));
        lblUsers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 39, 47), 1, true));
        jPanel2.add(lblUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 380, 120));

        lblOccupancy.setBackground(new java.awt.Color(35, 39, 47));
        lblOccupancy.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblOccupancy.setForeground(new java.awt.Color(242, 242, 242));
        lblOccupancy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 39, 47), 1, true));
        jPanel2.add(lblOccupancy, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 380, 120));

        lblRevenue.setBackground(new java.awt.Color(35, 39, 47));
        lblRevenue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRevenue.setForeground(new java.awt.Color(242, 242, 242));
        lblRevenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 39, 47), 1, true));
        jPanel2.add(lblRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 380, 120));

        jPanel1.setBackground(new java.awt.Color(35, 39, 47));
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 400, 120));

        jPanel3.setBackground(new java.awt.Color(35, 39, 47));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 400, 120));

        jPanel4.setBackground(new java.awt.Color(35, 39, 47));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 400, 120));

        jPanel5.setBackground(new java.awt.Color(35, 39, 47));
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 400, 120));

        jPanel6.setBackground(new java.awt.Color(35, 39, 47));
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 400, 120));

        jPanel7.setBackground(new java.awt.Color(35, 39, 47));
        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 400, 120));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cinemax Statistics");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 390, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        setSize(new java.awt.Dimension(914, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        int confirm =
                JOptionPane.showConfirmDialog(
                        this,
                        "Are you sure you want to logout?",
                        "Logout",
                        JOptionPane.YES_NO_OPTION);

        if(confirm !=
                JOptionPane.YES_OPTION){

            return;
        }

        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        new AdminDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnLoadReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadReportActionPerformed
        loadReport();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLoadReport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblBookings;
    private javax.swing.JLabel lblOccupancy;
    private javax.swing.JLabel lblRevenue;
    private javax.swing.JLabel lblShowtimes;
    private javax.swing.JLabel lblTotalMovies;
    private javax.swing.JLabel lblUsers;
    // End of variables declaration//GEN-END:variables
}
