package ui;
import dao.ShowTimeDAO;
import java.time.LocalDate;
import java.time.LocalTime;
import model.ShowTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ShowTimeFrame extends javax.swing.JFrame {
    
        private void loadShowTimes(){

        DefaultTableModel model =
                (DefaultTableModel)
                        tblShowTimes.getModel();

        model.setRowCount(0);

        ShowTimeDAO dao =
                new ShowTimeDAO();

        for(ShowTime s :
                dao.getAllShowTimes()){

            model.addRow(
            new Object[]{

                    s.getMovieTitle(),
                    s.getShowDate(),
                    s.getShowTime(),
                    s.getHallNo()
            });
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShowTimeFrame.class.getName());

    /**
     * Creates new form ShowTimeFrame
     */
    public ShowTimeFrame() {
    initComponents();
    loadShowTimes();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHollNo = new javax.swing.JTextField();
        btnAddShowTime = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowTimes = new javax.swing.JTable();
        btnDashboard = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEMAX - Show Time Manage");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Add Show Times");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 310, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Movie ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 90, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 250, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Time:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 90, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 250, 25));
        getContentPane().add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 250, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hall No:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 90, -1));
        getContentPane().add(txtHollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 250, 25));

        btnAddShowTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddShowTime.setText("Add Show Time");
        btnAddShowTime.addActionListener(this::btnAddShowTimeActionPerformed);
        getContentPane().add(btnAddShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 140, -1));

        tblShowTimes.setBorder(new javax.swing.border.MatteBorder(null));
        tblShowTimes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Title", "Date", "Time", "Hall No"
            }
        ));
        tblShowTimes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblShowTimes.setAutoscrolls(false);
        tblShowTimes.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblShowTimes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 780, 270));

        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard.setText("Back to Dashboard");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);
        getContentPane().add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        jPanel1.setBackground(new java.awt.Color(24, 26, 31));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(35, 39, 47));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 840, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(914, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddShowTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddShowTimeActionPerformed
        try{

            ShowTime showTime =
                    new ShowTime();

            showTime.setMovieId(
                    Integer.parseInt(
                            txtID.getText()));

            LocalDate.parse(
                    txtDate.getText());

            showTime.setShowDate(
                    txtDate.getText());

            LocalTime.parse(
                    txtTime.getText());

            showTime.setShowTime(
                    txtTime.getText());

            showTime.setHallNo(
                    Integer.parseInt(
                            txtHollNo.getText()));

            ShowTimeDAO dao =
                    new ShowTimeDAO();

            if(dao.addShowTime(showTime)){

                JOptionPane.showMessageDialog(
                        this,
                        "Show Time Added");

                loadShowTimes();

                txtID.setText("");
                txtDate.setText("");
                txtTime.setText("");
                txtHollNo.setText("");

            }else{

                JOptionPane.showMessageDialog(
                        this,
                        "Failed");
            }

        }catch(Exception e){

            JOptionPane.showMessageDialog(
                    this,
                    "Invalid Date or Time Format\n\n"
                    + "Date : YYYY-MM-DD\n"
                    + "Time : HH:MM:SS");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnAddShowTimeActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        new AdminDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ShowTimeFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddShowTime;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblShowTimes;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtHollNo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
